backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "data/products"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "Product Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Type", name: "type", widget: "string" }
      - { label: "Size", name: "size", widget: "string" }
      - { label: "Rating", name: "rating", widget: "number", default: 4.5 }
      - { label: "Storage", name: "storage", widget: "string", default: "No" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }

  - name: "mattresses"
    label: "Mattresses"
    folder: "data/mattresses"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Firmness", name: "firmness", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
